version: '3'

services:

  redis:
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379

  backend:
    depends_on:
    - redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:${PORT}"

