version: '3'

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379

  backend:
    container_name: backend
    image: suchencjusz/alljob-backend:latest
    depends_on:
    - redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:${PORT}"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 redis backend

